name: wiki-to-vue-press-action
description: GitHub Action building a Vue Press web site from the GitHub Wiki

runs:
  using: node12
  main: 'dist/index.js'

branding:
  icon: alert-triangle
  color: orange